// Stamps worker.generated.js from worker.template.js using the CSP artifacts
// generated by the M7 build in apps/pos/out. Also writes out/.assetsignore so
// the CSP deployment artifacts are never uploaded as public assets.
// A missing artifact fails loudly — never deploy a worker with a stale or
// absent CSP map (the header map and out/ deploy as one atomic unit).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../../apps/pos/out');

const routes = readFileSync(resolve(outDir, '.eden-csp-routes.json'), 'utf8').trim();
const union = readFileSync(resolve(outDir, '.eden-csp-union.txt'), 'utf8').trim();
if (routes.length === 0 || union.length === 0) throw new Error('empty CSP artifact');

const template = readFileSync(resolve(here, 'worker.template.js'), 'utf8');
const stamped = template
  .replace('__EDEN_ROUTE_HEADERS__', routes)
  .replace('__EDEN_UNION_HEADER__', JSON.stringify(union));
if (stamped.includes('__EDEN_')) throw new Error('unresolved placeholder in worker template');

writeFileSync(resolve(here, 'worker.generated.js'), stamped);
writeFileSync(resolve(outDir, '.assetsignore'), '.eden-csp-routes.json\n.eden-csp-union.txt\n.assetsignore\n');
console.log('stamped worker.generated.js from', outDir);
